// Package client wraps the generated client with what every request carries
// and what every response is checked for: the bearer token, the User-Agent
// naming this build, an Idempotency-Key on every write, and the version of the
// instance against pa's own (ADR 0011, docs/api.md).
package client

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"mime"
	"net"
	"net/http"
	"net/url"
	"os"
	"runtime"
	"strings"
	"time"

	"github.com/datavisionzero/planaffe/src/cli/internal/api"
	"github.com/datavisionzero/planaffe/src/cli/internal/config"
	"github.com/datavisionzero/planaffe/src/cli/internal/exit"
	"github.com/datavisionzero/planaffe/src/cli/internal/problem"
	"github.com/datavisionzero/planaffe/src/cli/internal/version"
)

// Failure is an answer pa turns into an exit code: what to print to stderr,
// and which code.
type Failure struct {
	Code    int
	Message string
	Problem *problem.Problem
}

func (f *Failure) Error() string { return f.Message }

// VersionHeader is what every response carries (ADR 0011).
const VersionHeader = "Planaffe-Version"

// IdempotencyHeader is sent on every write, generated by pa itself, so that no
// agent has to know the header exists (docs/api.md, Idempotency).
const IdempotencyHeader = "Idempotency-Key"

// Client is one invocation's client: one idempotency key, one user agent.
type Client struct {
	*api.ClientWithResponses
	key    string
	writes int
}

// New builds the client for cfg. The idempotency key is 32 hex characters per
// invocation, numbered per write: a command that writes several times —
// closing an epic and parking what was open — sends `<key>-1`, `<key>-2`, …,
// so that no two of its requests share a key. Two invocations never share a
// key, so running a command again is a new request and not a replay.
//
// What does replay is the transport: a write whose connection fails before any
// answer arrives is sent again, up to Attempts times in all, with the same
// key (docs/api.md, Idempotency). The instance answers the second from what it
// kept of the first, if the first got that far, so a `next --claim` whose
// answer was lost claims nothing twice.
func New(cfg config.Config, httpClient *http.Client) (*Client, error) {
	key := make([]byte, 16)
	if _, err := rand.Read(key); err != nil {
		return nil, err
	}

	c := &Client{key: hex.EncodeToString(key)}
	generated, err := api.NewClientWithResponses(
		cfg.URL,
		api.WithHTTPClient(Retrying(httpClient)),
		api.WithRequestEditorFn(func(_ context.Context, req *http.Request) error {
			// `login` is the one command that talks to an instance with nothing
			// in its hand; an empty bearer would be a token the door has to
			// refuse rather than a request that never presented one.
			if cfg.Token != "" {
				req.Header.Set("Authorization", "Bearer "+cfg.Token)
			}
			req.Header.Set("User-Agent", UserAgent())
			if req.Method != http.MethodGet && req.Method != http.MethodHead {
				c.writes++
				req.Header.Set(IdempotencyHeader, fmt.Sprintf("%s-%d", c.key, c.writes))
			}
			return nil
		}))
	if err != nil {
		return nil, err
	}

	c.ClientWithResponses = generated
	return c, nil
}

// ByAddress is what a call needs whose path parameter is an address rather
// than a name.
//
// A page in the knowledge base is reached by the slugs from the root down, and
// the slashes between them are the address itself (ADR 0028). `docs/api.md`
// says it outright: this is the one path parameter in the contract that
// contains slashes, and a client that percent-encodes them names nothing. The
// generated client escapes every path parameter whole, which is right for
// every other route — a release named with a slash still wants the escape — so
// the three calls that carry an address say so rather than the client changing
// its mind for all of them. The web application draws the same line in
// `byAddress`.
//
// The repair is to drop the escaped spelling the generator wrote. `URL.Path`
// already holds what was meant, separators and all; with no `RawPath` beside
// it, net/http writes the path it escapes itself, and that leaves a separator
// alone while still escaping everything else.
func ByAddress(_ context.Context, req *http.Request) error {
	req.URL.RawPath = ""
	return nil
}

// Attempts is how often a write is sent in all when its connection fails
// before an answer.
const Attempts = 3

// Backoff is the wait before the first repetition; each further one doubles it.
var Backoff = 250 * time.Millisecond

// Retrying is httpClient with a transport that sends a write again when its
// connection fails before any answer arrived — only a write, because only a
// write carries the Idempotency-Key that makes a second sending safe, and only
// then, because an answer of any status is the instance's word and is final.
// A deadline that ran out is not repeated either: the time was the caller's.
func Retrying(httpClient *http.Client) *http.Client {
	wrapped := *httpClient
	base := httpClient.Transport
	if base == nil {
		base = http.DefaultTransport
	}
	wrapped.Transport = retrying{base: base}
	return &wrapped
}

type retrying struct{ base http.RoundTripper }

func (r retrying) RoundTrip(req *http.Request) (*http.Response, error) {
	resp, err := r.base.RoundTrip(req)
	if req.Header.Get(IdempotencyHeader) == "" || (req.Body != nil && req.GetBody == nil) {
		return resp, err
	}

	wait := Backoff
	for attempt := 1; err != nil && attempt < Attempts && req.Context().Err() == nil; attempt++ {
		select {
		case <-req.Context().Done():
			return resp, err
		case <-time.After(wait):
		}
		wait *= 2

		again := req.Clone(req.Context())
		if req.GetBody != nil {
			body, bodyErr := req.GetBody()
			if bodyErr != nil {
				return resp, err
			}
			again.Body = body
		}
		resp, err = r.base.RoundTrip(again)
	}
	return resp, err
}

// UserAgent is `pa/<version> (<os>/<arch>)`.
func UserAgent() string {
	return fmt.Sprintf("pa/%s (%s/%s)", version.Version, runtime.GOOS, runtime.GOARCH)
}

// Default is the HTTP client pa uses: a timeout, because an agent must never
// hang on a request that is not a `--wait`.
func Default() *http.Client {
	return &http.Client{Timeout: 30 * time.Second}
}

// ForWait leaves room for the server-held request while retaining a transport
// deadline if the instance never answers. Server rounds are at most one hour.
func ForWait(seconds int) *http.Client {
	return &http.Client{Timeout: time.Duration(seconds)*time.Second + 30*time.Second}
}

// Check turns a response into a Failure when it is one: the version skew first,
// because a skewed instance's refusal may be about a shape pa does not know;
// then a success that is not the JSON it claims to be; then the problem
// document by the table of docs/api.md.
func Check(resp *http.Response, body []byte) error {
	if resp == nil {
		return &Failure{Code: exit.Unexpected, Message: "no response"}
	}

	if ok, reason := version.Compatible(version.Version, resp.Header.Get(VersionHeader)); !ok {
		return &Failure{Code: exit.Skew, Message: reason}
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		return notJSON(resp, body)
	}

	p := problem.Parse(body)
	code := exit.FromResponse(resp.StatusCode, p)
	message := p.Message()
	if message == "" {
		message = fmt.Sprintf("the instance answered %s", resp.Status)
		// No problem document on a 404 or a 405 is the older instance's answer
		// to an endpoint this build knows and that one does not — the sibling
		// of the HTML case in notJSON, and it deserves the same sentence.
		if resp.StatusCode == http.StatusNotFound || resp.StatusCode == http.StatusMethodNotAllowed {
			message += " with no problem document — most likely it does not have this endpoint yet; `pa version` says what it is"
		}
	}

	return &Failure{Code: code, Message: message, Problem: p}
}

// notJSON catches a success that is not the shape the contract promises, and
// it is the one answer pa cannot tell from a good one by its status alone.
//
// The instance serves the web application from the same port and falls back to
// `index.html` for every path no endpoint took (`docs/codebase.md`). So an
// endpoint this build of pa knows and that instance does not answers 200 with
// a page of HTML — a success, to every check there was. Every verb then
// dereferenced the JSON the generated client had not filled in, and pa died on
// a nil pointer instead of saying what was wrong. Ninety-nine of those
// dereferences: the guard belongs here rather than at each of them.
func notJSON(resp *http.Response, body []byte) error {
	// A 204 and anything else that answers with nothing is a fine success.
	if len(body) == 0 {
		return nil
	}

	kind, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
	if err == nil && (kind == "application/json" || strings.HasSuffix(kind, "+json")) {
		return nil
	}

	where := ""
	if resp.Request != nil && resp.Request.URL != nil {
		where = " for " + resp.Request.URL.Path
	}

	return &Failure{
		Code: exit.Unexpected,
		Message: fmt.Sprintf(
			"the instance answered %s%s with %s, not JSON — most likely it does not have this endpoint yet; `pa version` says what it is",
			resp.Status, where, described(kind)),
	}
}

func described(kind string) string {
	if kind == "" {
		return "something else"
	}
	return kind
}

// Transport turns an error from the HTTP client into the Failure it is: the
// instance could not be reached, exit 10.
func Transport(err error) error {
	if err == nil {
		return nil
	}

	var failure *Failure
	if errors.As(err, &failure) {
		return failure
	}

	var urlErr *url.Error
	var netErr net.Error
	if errors.As(err, &urlErr) || errors.As(err, &netErr) || errors.Is(err, context.DeadlineExceeded) || errors.Is(err, os.ErrDeadlineExceeded) {
		return &Failure{Code: exit.Unreachable, Message: fmt.Sprintf("the instance could not be reached: %v", err)}
	}

	return &Failure{Code: exit.Unexpected, Message: err.Error()}
}
