using System.Security.Cryptography;
using System.Text;
using Planaffe.Application.Ports;
using Planaffe.Domain;

namespace Planaffe.Api.Http;

/// <summary>
/// <c>Idempotency-Key</c> on every write (<c>docs/api.md</c>, Idempotency):
/// the reply to a write is kept under the caller's identity and the key for 24
/// hours, and a replay with the same key and the same request — method, path
/// and body — is answered from the store with the original status and body.
/// The same key with a different request is <c>idempotency-mismatch</c>.
/// </summary>
/// <remarks>
/// <para>
/// A middleware rather than something the acts know about: the CLI sends a key
/// on every write, generated by itself, and no agent has to know the header
/// exists. This is what makes a retry safe on the two writes where it is not
/// safe by nature — a bulk create replayed without it creates the seven issues
/// twice, and <c>next</c> replayed without it claims a second issue.
/// </para>
/// <para>
/// Only a caller's writes are stored: the key is half identity, and a request
/// that never got past the door has no identity to keep it under. Answers of
/// 500 are not stored either — a retry after a bug should get to try.
/// </para>
/// <para>
/// The row is written before the write runs, pending, and conditionally on the
/// key: of two twins sent at once — a client that retried while the first was
/// still being answered — exactly one runs, and the other waits for its answer
/// and replays it, or is told <c>idempotency-pending</c> when that takes longer
/// than <see cref="TwinWait"/>. <c>Location</c> and <c>ETag</c> are kept with
/// the answer and replayed with it.
/// </para>
/// <para>
/// A write whose answer carries a secret that is shown once — a token, a
/// device code, an access link — says so with <see cref="ShownOnce"/>, and of
/// its success only the status is kept. The store holds nothing a copy of the
/// database could sign in with, and a replay is refused as
/// <c>already-shown</c>: the secret exists, the first answer was the one
/// chance to see it, and whoever lost it revokes it and asks for another.
/// </para>
/// </remarks>
public sealed class IdempotencyMiddleware(RequestDelegate next, TimeProvider clock)
{
    public const string Header = "Idempotency-Key";

    public const int MaximumKeyLength = 200;

    public static readonly TimeSpan Lifetime = TimeSpan.FromHours(24);

    /// <summary>
    /// How long a pending row holds its key: longer than any request runs —
    /// the longest is a <c>next</c> waiting its hour — so that only the row of
    /// a process that went away mid-request is ever taken over.
    /// </summary>
    public static readonly TimeSpan PendingLifetime = TimeSpan.FromMinutes(65);

    /// <summary>How long a twin waits for the first request's answer before it is <c>idempotency-pending</c>.</summary>
    public static readonly TimeSpan TwinWait = TimeSpan.FromSeconds(10);

    private static readonly TimeSpan TwinPoll = TimeSpan.FromMilliseconds(100);

    public async Task InvokeAsync(HttpContext context)
    {
        var key = context.Request.Headers[Header].ToString();
        if (string.IsNullOrEmpty(key) || !IsWrite(context.Request.Method) || context.Features.Get<Caller>() is not { } caller)
        {
            await next(context);
            return;
        }

        if (key.Length > MaximumKeyLength)
        {
            throw Refusal.Validation(Header, $"An idempotency key is at most {MaximumKeyLength} characters.");
        }

        var store = context.RequestServices.GetRequiredService<IIdempotency>();
        var hash = await HashAsync(context.Request, context.RequestAborted);
        var waitUntil = clock.GetUtcNow() + TwinWait;

        // Either this request writes the pending row and runs, or a twin did
        // and this one is answered with what the twin was answered — once the
        // twin has its answer, which is what the wait is for.
        while (true)
        {
            var stored = await store.FindAsync(caller.Id, key, context.RequestAborted);
            var now = clock.GetUtcNow();
            if (stored is not null && now - stored.CreatedAt < Lifetime
                && !(stored.Pending && now - stored.CreatedAt >= PendingLifetime))
            {
                if (!stored.RequestHash.AsSpan().SequenceEqual(hash))
                {
                    throw new Refusal(
                        RefusalCode.IdempotencyMismatch,
                        $"The {Header} {key} was used for a different request; a key names one request.");
                }

                if (stored.Pending)
                {
                    if (now >= waitUntil)
                    {
                        throw new Refusal(
                            RefusalCode.IdempotencyPending,
                            $"The request with {Header} {key} is still being answered; send it again once it is, and it is answered from the store.");
                    }

                    await Task.Delay(TwinPoll, clock, context.RequestAborted);
                    continue;
                }

                if (stored.Withheld)
                {
                    throw new Refusal(
                        RefusalCode.AlreadyShown,
                        $"The request with {Header} {key} was answered with a secret, which is shown once and was not kept; revoke what it created if the answer was lost, and ask for another.",
                        stored.Location is null ? null : new Dictionary<string, object?> { ["location"] = stored.Location });
                }

                await ReplayAsync(context, stored);
                return;
            }

            if (await store.TryBeginAsync(caller.Id, key, hash, now, Lifetime, PendingLifetime, context.RequestAborted))
            {
                break;
            }
        }

        await RunAsync(context, store, caller, key, hash);
    }

    private async Task RunAsync(HttpContext context, IIdempotency store, Caller caller, string key, byte[] hash)
    {
        var original = context.Response.Body;
        await using var buffer = new MemoryStream();
        context.Response.Body = buffer;
        var kept = false;

        try
        {
            try
            {
                await next(context);
            }
            catch (Refusal refusal)
            {
                // A refused write is an answer too, and a replay gets the same
                // one; the document is written here, in the handler's stead,
                // so that it is what gets stored.
                await Problems.WriteAsync(context, refusal);
            }

            var status = context.Response.StatusCode;
            if (status < StatusCodes.Status500InternalServerError)
            {
                // A refusal carries no secret and is kept like any other.
                var withheld = status < StatusCodes.Status400BadRequest
                    && context.GetEndpoint()?.Metadata.GetMetadata<ShownOnce>() is not null;
                var body = withheld || buffer.Length == 0 ? null : Encoding.UTF8.GetString(buffer.ToArray());
                var headers = context.Response.Headers;
                var reply = new StoredReply(hash, (short)status, body, clock.GetUtcNow(), withheld,
                    NullIfEmpty(headers.Location.ToString()), NullIfEmpty(headers.ETag.ToString()));

                // Not the request's token: a caller that went away after the
                // write committed is exactly the one whose retry must find it.
                await store.CompleteAsync(caller.Id, key, reply, CancellationToken.None);
                kept = true;
            }
        }
        finally
        {
            if (!kept)
            {
                await store.AbandonAsync(caller.Id, key, CancellationToken.None);
            }

            context.Response.Body = original;
            buffer.Position = 0;
            await buffer.CopyToAsync(original, context.RequestAborted);
        }
    }

    private static string? NullIfEmpty(string value) => value.Length == 0 ? null : value;

    private static bool IsWrite(string method) =>
        HttpMethods.IsPost(method) || HttpMethods.IsPatch(method) || HttpMethods.IsDelete(method) || HttpMethods.IsPut(method);

    // Method, path with query, and the body bytes as sent: what makes two
    // requests the same request.
    private static async Task<byte[]> HashAsync(HttpRequest request, CancellationToken cancellationToken)
    {
        request.EnableBuffering();

        using var sha = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        sha.AppendData(Encoding.UTF8.GetBytes(request.Method));
        sha.AppendData("\n"u8);
        sha.AppendData(Encoding.UTF8.GetBytes(request.Path + request.QueryString));
        sha.AppendData("\n"u8);

        var body = new byte[16 * 1024];
        int read;
        while ((read = await request.Body.ReadAsync(body, cancellationToken)) > 0)
        {
            sha.AppendData(body.AsSpan(0, read));
        }

        request.Body.Position = 0;
        return sha.GetHashAndReset();
    }

    private static async Task ReplayAsync(HttpContext context, StoredReply stored)
    {
        context.Response.StatusCode = stored.Status!.Value;
        context.Response.Headers["Idempotent-Replayed"] = "true";
        if (stored.Location is not null)
        {
            context.Response.Headers.Location = stored.Location;
        }

        if (stored.ETag is not null)
        {
            context.Response.Headers.ETag = stored.ETag;
        }

        if (stored.Body is null)
        {
            return;
        }

        context.Response.ContentType = stored.Status >= StatusCodes.Status400BadRequest ? Problems.ContentType : "application/json; charset=utf-8";
        await context.Response.WriteAsync(stored.Body, context.RequestAborted);
    }
}

/// <summary>
/// Endpoint metadata: the success of this write carries a secret that is shown
/// once, so the idempotency store keeps its status and not its body.
/// </summary>
public sealed class ShownOnce
{
    public static readonly ShownOnce Instance = new();

    private ShownOnce()
    {
    }
}

public static class IdempotencyMiddlewareExtensions
{
    /// <summary>
    /// Marks a write whose success carries a secret shown once
    /// (<see cref="ShownOnce"/>); its replay is the 409 <c>already-shown</c>.
    /// </summary>
    public static RouteHandlerBuilder ShownOnce(this RouteHandlerBuilder builder) =>
        builder.WithMetadata(Http.ShownOnce.Instance).ProducesProblem(StatusCodes.Status409Conflict);

    /// <summary>After authentication — the key is half identity — and before the endpoints.</summary>
    public static IApplicationBuilder UsePlanaffeIdempotency(this IApplicationBuilder app) => app.UseMiddleware<IdempotencyMiddleware>();
}
