using System.Security.Cryptography;
using System.Text;
using Planaffe.Application.Ports;
using Planaffe.Domain;

namespace Planaffe.Api.Http;

/// <summary>
/// <c>Idempotency-Key</c> on every write (<c>docs/api.md</c>, Idempotency):
/// the reply to a write is kept under the caller's identity and the key for 24
/// hours, and a replay with the same key and the same request — method, path
/// and body — is answered from the store with the original status and body.
/// The same key with a different request is <c>idempotency-mismatch</c>.
/// </summary>
/// <remarks>
/// <para>
/// A middleware rather than something the acts know about: the CLI sends a key
/// on every write, generated by itself, and no agent has to know the header
/// exists. This is what makes a retry safe on the two writes where it is not
/// safe by nature — a bulk create replayed without it creates the seven issues
/// twice, and <c>next</c> replayed without it claims a second issue.
/// </para>
/// <para>
/// Only a caller's writes are stored: the key is half identity, and a request
/// that never got past the door has no identity to keep it under. Answers of
/// 500 are not stored either — a retry after a bug should get to try.
/// </para>
/// </remarks>
public sealed class IdempotencyMiddleware(RequestDelegate next, TimeProvider clock)
{
    public const string Header = "Idempotency-Key";

    public const int MaximumKeyLength = 200;

    public static readonly TimeSpan Lifetime = TimeSpan.FromHours(24);

    public async Task InvokeAsync(HttpContext context)
    {
        var key = context.Request.Headers[Header].ToString();
        if (string.IsNullOrEmpty(key) || !IsWrite(context.Request.Method) || context.Features.Get<Caller>() is not { } caller)
        {
            await next(context);
            return;
        }

        if (key.Length > MaximumKeyLength)
        {
            throw Refusal.Validation(Header, $"An idempotency key is at most {MaximumKeyLength} characters.");
        }

        var store = context.RequestServices.GetRequiredService<IIdempotency>();
        var hash = await HashAsync(context.Request, context.RequestAborted);
        var now = clock.GetUtcNow();

        var stored = await store.FindAsync(caller.Id, key, context.RequestAborted);
        if (stored is not null && now - stored.CreatedAt < Lifetime)
        {
            if (!stored.RequestHash.AsSpan().SequenceEqual(hash))
            {
                throw new Refusal(
                    RefusalCode.IdempotencyMismatch,
                    $"The {Header} {key} was used for a different request; a key names one request.");
            }

            await ReplayAsync(context, stored);
            return;
        }

        var original = context.Response.Body;
        await using var buffer = new MemoryStream();
        context.Response.Body = buffer;

        try
        {
            try
            {
                await next(context);
            }
            catch (Refusal refusal)
            {
                // A refused write is an answer too, and a replay gets the same
                // one; the document is written here, in the handler's stead,
                // so that it is what gets stored.
                await Problems.WriteAsync(context, refusal);
            }

            if (context.Response.StatusCode < StatusCodes.Status500InternalServerError)
            {
                var body = buffer.Length == 0 ? null : Encoding.UTF8.GetString(buffer.ToArray());
                await store.StoreAsync(caller.Id, key, new StoredReply(hash, (short)context.Response.StatusCode, body, now), context.RequestAborted);
            }
        }
        finally
        {
            context.Response.Body = original;
            buffer.Position = 0;
            await buffer.CopyToAsync(original, context.RequestAborted);
        }
    }

    private static bool IsWrite(string method) =>
        HttpMethods.IsPost(method) || HttpMethods.IsPatch(method) || HttpMethods.IsDelete(method) || HttpMethods.IsPut(method);

    // Method, path with query, and the body bytes as sent: what makes two
    // requests the same request.
    private static async Task<byte[]> HashAsync(HttpRequest request, CancellationToken cancellationToken)
    {
        request.EnableBuffering();

        using var sha = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        sha.AppendData(Encoding.UTF8.GetBytes(request.Method));
        sha.AppendData("\n"u8);
        sha.AppendData(Encoding.UTF8.GetBytes(request.Path + request.QueryString));
        sha.AppendData("\n"u8);

        var body = new byte[16 * 1024];
        int read;
        while ((read = await request.Body.ReadAsync(body, cancellationToken)) > 0)
        {
            sha.AppendData(body.AsSpan(0, read));
        }

        request.Body.Position = 0;
        return sha.GetHashAndReset();
    }

    private static async Task ReplayAsync(HttpContext context, StoredReply stored)
    {
        context.Response.StatusCode = stored.Status;
        context.Response.Headers["Idempotent-Replayed"] = "true";

        if (stored.Body is null)
        {
            return;
        }

        context.Response.ContentType = stored.Status >= StatusCodes.Status400BadRequest ? Problems.ContentType : "application/json; charset=utf-8";
        await context.Response.WriteAsync(stored.Body, context.RequestAborted);
    }
}

public static class IdempotencyMiddlewareExtensions
{
    /// <summary>After authentication — the key is half identity — and before the endpoints.</summary>
    public static IApplicationBuilder UsePlanaffeIdempotency(this IApplicationBuilder app) => app.UseMiddleware<IdempotencyMiddleware>();
}
