// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planaffe.Infrastructure.Persistence;

#nullable disable

namespace Planaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlanaffeDbContext))]
    partial class PlanaffeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Planaffe.Domain.Epics.Epic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_epic");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("epic_number");

                    b.ToTable("epic", null, t =>
                        {
                            t.HasCheckConstraint("ck_epic_closed", "(status = 'closed') = (closed_at is not null)");

                            t.HasCheckConstraint("ck_epic_status", "status in ('open', 'closed')");
                        });
                });

            modelBuilder.Entity("Planaffe.Domain.Epics.EpicLabel", b =>
                {
                    b.Property<Guid>("EpicId")
                        .HasColumnType("uuid")
                        .HasColumnName("epic_id");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.HasKey("EpicId", "LabelId")
                        .HasName("pk_epic_label");

                    b.ToTable("epic_label", (string)null);
                });

            modelBuilder.Entity("Planaffe.Domain.History.HistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("EpicId")
                        .HasColumnType("uuid")
                        .HasColumnName("epic_id");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<Guid?>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.HasKey("Id")
                        .HasName("pk_history");

                    b.HasIndex("EpicId", "Id")
                        .HasDatabaseName("history_epic");

                    b.HasIndex("IssueId", "Id")
                        .HasDatabaseName("history_issue");

                    b.ToTable("history", null, t =>
                        {
                            t.HasCheckConstraint("ck_history_subject", "num_nonnulls(issue_id, epic_id) = 1");
                        });
                });

            modelBuilder.Entity("Planaffe.Domain.Identities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Administrator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("administrator");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_identity");

                    b.ToTable("identity", null, t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", "kind in ('user', 'agent')");

                            t.HasCheckConstraint("ck_identity_owner", "kind = 'user' and owner_id is null or kind = 'agent' and owner_id is not null and not administrator");
                        });

                    b.HasDiscriminator<string>("kind").HasValue("Identity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Planaffe.Domain.Identities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_token");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("token_agent")
                        .HasFilter("kind = 'agent'");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("token_secret_hash");

                    b.ToTable("token", null, t =>
                        {
                            t.HasCheckConstraint("ck_token_kind", "kind in ('user', 'agent')");
                        });
                });

            modelBuilder.Entity("Planaffe.Domain.Issues.Blocker", b =>
                {
                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_id");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.HasKey("BlockerId", "BlockedId")
                        .HasName("pk_blocker");

                    b.HasIndex("BlockedId")
                        .HasDatabaseName("blocker_blocked");

                    b.ToTable("blocker", null, t =>
                        {
                            t.HasCheckConstraint("ck_blocker_not_self", "blocker_id <> blocked_id");
                        });
                });

            modelBuilder.Entity("Planaffe.Domain.Issues.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("IssueId", "CreatedAt")
                        .HasDatabaseName("comment_issue");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("Planaffe.Domain.Issues.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<Guid?>("EpicId")
                        .HasColumnType("uuid")
                        .HasColumnName("epic_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<short>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<bool>("Ready")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ready");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("todo")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_issue");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("issue_assignee")
                        .HasFilter("assignee_id is not null");

                    b.HasIndex("EpicId")
                        .HasDatabaseName("issue_epic")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("issue_number");

                    b.HasIndex("ProjectId", "UpdatedAt", "Id")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("issue_updated")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("ProjectId", "Priority", "CreatedAt", "Number")
                        .IsDescending(false, true, false, false)
                        .HasDatabaseName("issue_next")
                        .HasFilter("deleted_at is null");

                    b.ToTable("issue", null, t =>
                        {
                            t.HasCheckConstraint("ck_issue_claim_columns", "(claimed_by is null) = (claimed_at is null) and (claimed_by is null) = (claim_extended_at is null)");

                            t.HasCheckConstraint("ck_issue_claimed", "(status = 'in_progress') = (claimed_by is not null)");

                            t.HasCheckConstraint("ck_issue_closed", "(status in ('done', 'canceled')) = (closed_at is not null)");

                            t.HasCheckConstraint("ck_issue_priority", "priority between 0 and 4");

                            t.HasCheckConstraint("ck_issue_status", "status in ('backlog', 'todo', 'in_progress', 'review', 'done', 'canceled')");
                        });
                });

            modelBuilder.Entity("Planaffe.Domain.Issues.IssueLabel", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.HasKey("IssueId", "LabelId")
                        .HasName("pk_issue_label");

                    b.ToTable("issue_label", (string)null);
                });

            modelBuilder.Entity("Planaffe.Domain.Issues.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid?>("AnsweredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("answered_by");

                    b.Property<DateTimeOffset>("AskedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asked_at");

                    b.Property<Guid>("AskedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("asked_by");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.HasKey("Id")
                        .HasName("pk_question");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("question_open")
                        .HasFilter("answer is null");

                    b.HasIndex("IssueId", "AskedAt")
                        .HasDatabaseName("question_issue");

                    b.ToTable("question", null, t =>
                        {
                            t.HasCheckConstraint("ck_question_answer", "(answer is null) = (answered_by is null) and (answer is null) = (answered_at is null)");
                        });
                });

            modelBuilder.Entity("Planaffe.Domain.Projects.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Group")
                        .HasColumnType("text")
                        .HasColumnName("label_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_label");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("label_name");

                    b.ToTable("label", (string)null);
                });

            modelBuilder.Entity("Planaffe.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("LastEpicNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_epic_number");

                    b.Property<int>("LastIssueNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_issue_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("ReviewRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("review_required");

                    b.Property<bool>("TriageRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("triage_required");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("project_key");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("Planaffe.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Body")
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_hash");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("IdentityId", "Key")
                        .HasName("pk_idempotency");

                    b.ToTable("idempotency", (string)null);
                });

            modelBuilder.Entity("Planaffe.Infrastructure.Persistence.IssueRead", b =>
                {
                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset?>("ClaimExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_expires_at");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<Guid?>("ClaimedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("EpicId")
                        .HasColumnType("uuid")
                        .HasColumnName("epic_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<bool>("Ready")
                        .HasColumnType("boolean")
                        .HasColumnName("ready");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ToTable((string)null);

                    b.ToView("issue_read", (string)null);
                });

            modelBuilder.Entity("Planaffe.Domain.Identities.Agent", b =>
                {
                    b.HasBaseType("Planaffe.Domain.Identities.Identity");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", "kind in ('user', 'agent')");

                            t.HasCheckConstraint("ck_identity_owner", "kind = 'user' and owner_id is null or kind = 'agent' and owner_id is not null and not administrator");
                        });

                    b.HasDiscriminator().HasValue("agent");
                });

            modelBuilder.Entity("Planaffe.Domain.Identities.User", b =>
                {
                    b.HasBaseType("Planaffe.Domain.Identities.Identity");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", "kind in ('user', 'agent')");

                            t.HasCheckConstraint("ck_identity_owner", "kind = 'user' and owner_id is null or kind = 'agent' and owner_id is not null and not administrator");
                        });

                    b.HasDiscriminator().HasValue("user");
                });

            modelBuilder.Entity("Planaffe.Domain.Epics.Epic", b =>
                {
                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_epic_created_by");

                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_epic_deleted_by");

                    b.HasOne("Planaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epic_project");
                });

            modelBuilder.Entity("Planaffe.Domain.Epics.EpicLabel", b =>
                {
                    b.HasOne("Planaffe.Domain.Epics.Epic", null)
                        .WithMany()
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epic_label_epic");

                    b.HasOne("Planaffe.Domain.Projects.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epic_label_label");
                });

            modelBuilder.Entity("Planaffe.Domain.History.HistoryEntry", b =>
                {
                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_history_actor");

                    b.HasOne("Planaffe.Domain.Epics.Epic", null)
                        .WithMany()
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_history_epic");

                    b.HasOne("Planaffe.Domain.Issues.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_history_issue");
                });

            modelBuilder.Entity("Planaffe.Domain.Identities.Token", b =>
                {
                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_token_identity");
                });

            modelBuilder.Entity("Planaffe.Domain.Issues.Blocker", b =>
                {
                    b.HasOne("Planaffe.Domain.Issues.Issue", null)
                        .WithMany()
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocker_blocked");

                    b.HasOne("Planaffe.Domain.Issues.Issue", null)
                        .WithMany()
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocker_blocker");

                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_blocker_created_by");
                });

            modelBuilder.Entity("Planaffe.Domain.Issues.Comment", b =>
                {
                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_comment_author");

                    b.HasOne("Planaffe.Domain.Issues.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_issue");
                });

            modelBuilder.Entity("Planaffe.Domain.Issues.Issue", b =>
                {
                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_issue_assignee");

                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_issue_author");

                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_issue_deleted_by");

                    b.HasOne("Planaffe.Domain.Epics.Epic", null)
                        .WithMany()
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_issue_epic");

                    b.HasOne("Planaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_project");

                    b.OwnsOne("Planaffe.Domain.Issues.Claim", "Claim", b1 =>
                        {
                            b1.Property<Guid>("IssueId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("ClaimedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("claimed_at");

                            b1.Property<DateTimeOffset?>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("claim_expires_at");

                            b1.Property<DateTimeOffset>("ExtendedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("claim_extended_at");

                            b1.Property<Guid>("HolderId")
                                .HasColumnType("uuid")
                                .HasColumnName("claimed_by");

                            b1.HasKey("IssueId");

                            b1.HasIndex("HolderId")
                                .HasDatabaseName("issue_claim")
                                .HasFilter("claimed_by is not null");

                            b1.ToTable("issue");

                            b1.HasOne("Planaffe.Domain.Identities.Identity", null)
                                .WithMany()
                                .HasForeignKey("HolderId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired()
                                .HasConstraintName("fk_issue_claimed_by");

                            b1.WithOwner()
                                .HasForeignKey("IssueId");
                        });

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Planaffe.Domain.Issues.IssueLabel", b =>
                {
                    b.HasOne("Planaffe.Domain.Issues.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_label_issue");

                    b.HasOne("Planaffe.Domain.Projects.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_label_label");
                });

            modelBuilder.Entity("Planaffe.Domain.Issues.Question", b =>
                {
                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("AnsweredBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_question_answered_by");

                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("AskedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_question_asked_by");

                    b.HasOne("Planaffe.Domain.Issues.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_issue");
                });

            modelBuilder.Entity("Planaffe.Domain.Projects.Label", b =>
                {
                    b.HasOne("Planaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_label_project");
                });

            modelBuilder.Entity("Planaffe.Domain.Projects.Project", b =>
                {
                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_project_created_by");

                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_project_deleted_by");
                });

            modelBuilder.Entity("Planaffe.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_identity");
                });

            modelBuilder.Entity("Planaffe.Domain.Identities.Agent", b =>
                {
                    b.HasOne("Planaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_identity_owner");
                });
#pragma warning restore 612, 618
        }
    }
}
